// AUTO-GENERATED by scripts/build-catalogue.js. Do not edit.
// Source of truth: catalogue/_collections/<slug>/meta.json and cover image. Run `npm run catalogue`.

export interface Collection {
  slug: string
  name: string
  /** e.g. "Festive 2026". May be empty. */
  season: string
  /** YYYY-MM-DD */
  releaseDate: string
  description: string
  /** Sort position; lower first. Ties broken by newest release. */
  order: number
  /** 1600x900 webp. */
  coverImage: string
}

export const collections: Collection[] = [
  {
    "slug": "deepawali-2026",
    "name": "Deepawali 2026",
    "season": "Festive 2026",
    "releaseDate": "2026-10-06",
    "description": "The label's first release. Festive dressing for men and women, from kurta sets and anarkalis to evening suits and gowns, finished with hand embroidery from Delhi.",
    "order": 10,
    "coverImage": "/images/shop/collections/deepawali-2026.webp"
  },
  {
    "slug": "winter-2026",
    "name": "Winter 2026",
    "season": "Festive 2026",
    "releaseDate": "2026-10-06",
    "description": "The label's first release. Festive dressing for men and women, from kurta sets and anarkalis to evening suits and gowns, finished with hand embroidery from Delhi.",
    "order": 10,
    "coverImage": "/images/shop/collections/winter-2026.webp"
  }
]
