// AUTO-GENERATED by scripts/build-catalogue.js. Do not edit.
// Source of truth: catalogue/<slug>/meta.json and photos. Run `npm run catalogue`.

export type ProductCategory = "menswear" | "womenswear"

export interface Product {
  slug: string
  name: string
  category: ProductCategory
  description: string
  /** Price in paise. */
  price: number
  sizes: string[]
  /** Sort position within its category; lower first. */
  order: number
  /** Gallery images, cover first. 1200x1600 webp. */
  images: string[]
  coverImage: string
  /** 300x400 webp used in bag, checkout and order emails. */
  coverThumbnail: string
}

export const products: Product[] = [
  {
    "slug": "5dress",
    "name": "Style 5",
    "category": "menswear",
    "description": "",
    "price": 1599000,
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "order": 10,
    "images": [
      "/images/shop/items/5dress/5dress-cover.webp",
      "/images/shop/items/5dress/5dress-1.webp",
      "/images/shop/items/5dress/5dress-2.webp",
      "/images/shop/items/5dress/5dress-3.webp",
      "/images/shop/items/5dress/5dress-4.webp",
      "/images/shop/items/5dress/5dress-5.webp"
    ],
    "coverImage": "/images/shop/items/5dress/5dress-cover.webp",
    "coverThumbnail": "/images/shop/thumbnails/5dress/5dress-cover.webp"
  },
  {
    "slug": "2dress",
    "name": "Style 2",
    "category": "womenswear",
    "description": "",
    "price": 1099000,
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "order": 10,
    "images": [
      "/images/shop/items/2dress/2dress-cover.webp",
      "/images/shop/items/2dress/2dress-1.webp",
      "/images/shop/items/2dress/2dress-2.webp",
      "/images/shop/items/2dress/2dress-3.webp"
    ],
    "coverImage": "/images/shop/items/2dress/2dress-cover.webp",
    "coverThumbnail": "/images/shop/thumbnails/2dress/2dress-cover.webp"
  }
]
