// AUTO-GENERATED by scripts/build-catalogue.js. Do not edit.
// Source of truth: catalogue/taxonomy.json, catalogue/<slug>/meta.json and photos. Run `npm run catalogue`.

export type ProductCategory = "menswear" | "womenswear"

export interface Classification {
  slug: string
  title: string
}

export interface Product {
  slug: string
  name: string
  category: ProductCategory
  /** Slug from catalogue/taxonomy.json. */
  classification: string
  /** Slug of the release it belongs to (lib/data/collections.ts), or null. */
  collection: string | null
  /** YYYY-MM-DD. Inherited from the collection unless overridden. */
  releaseDate: string
  description: string
  /** Price in paise. */
  price: number
  sizes: string[]
  /** Manual bestseller flag, used only until real sales data exists. */
  bestseller: boolean
  /** Sort position within its category; lower first. */
  order: number
  /** Gallery images, cover first. 1200x1600 webp. */
  images: string[]
  coverImage: string
  /** 300x400 webp used in bag, checkout and order emails. */
  coverThumbnail: string
}

/** Classifications in menu order. */
export const classifications: Classification[] = [
  {
    "slug": "ethnic-wear",
    "title": "Ethnic Wear"
  },
  {
    "slug": "leisurewear",
    "title": "Leisurewear"
  },
  {
    "slug": "cocktail-formalwear",
    "title": "Cocktail & Formalwear"
  },
  {
    "slug": "outerwear",
    "title": "Outerwear"
  }
]

export const products: Product[] = [
  {
    "slug": "noir-bespoke-suit",
    "name": "Noir Bespoke Suit",
    "category": "menswear",
    "classification": "cocktail-formalwear",
    "collection": "deepawali-2026",
    "releaseDate": "2026-10-06",
    "description": "",
    "price": 1599000,
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "bestseller": true,
    "order": 10,
    "images": [
      "/images/shop/items/noir-bespoke-suit/noir-bespoke-suit-cover.webp",
      "/images/shop/items/noir-bespoke-suit/noir-bespoke-suit-1.webp",
      "/images/shop/items/noir-bespoke-suit/noir-bespoke-suit-2.webp",
      "/images/shop/items/noir-bespoke-suit/noir-bespoke-suit-3.webp",
      "/images/shop/items/noir-bespoke-suit/noir-bespoke-suit-4.webp",
      "/images/shop/items/noir-bespoke-suit/noir-bespoke-suit-5.webp"
    ],
    "coverImage": "/images/shop/items/noir-bespoke-suit/noir-bespoke-suit-cover.webp",
    "coverThumbnail": "/images/shop/thumbnails/noir-bespoke-suit/noir-bespoke-suit-cover.webp"
  },
  {
    "slug": "diva-ball-gown",
    "name": "Diva Ball Gown",
    "category": "womenswear",
    "classification": "cocktail-formalwear",
    "collection": "deepawali-2026",
    "releaseDate": "2026-10-06",
    "description": "",
    "price": 1099000,
    "sizes": [
      "S",
      "M",
      "L",
      "XL"
    ],
    "bestseller": true,
    "order": 10,
    "images": [
      "/images/shop/items/diva-ball-gown/diva-ball-gown-cover.webp",
      "/images/shop/items/diva-ball-gown/diva-ball-gown-1.webp",
      "/images/shop/items/diva-ball-gown/diva-ball-gown-2.webp",
      "/images/shop/items/diva-ball-gown/diva-ball-gown-3.webp"
    ],
    "coverImage": "/images/shop/items/diva-ball-gown/diva-ball-gown-cover.webp",
    "coverThumbnail": "/images/shop/thumbnails/diva-ball-gown/diva-ball-gown-cover.webp"
  }
]
