
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'RETURN_REQUESTED';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'RETURN_RECEIVED';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'EXCHANGE_DISPATCHED';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'EXCHANGE_COMPLETED';
